include:
  - project: 'shared/gitlab-ci-includes'
    ref: main
    file:
      - '/base.yml'
      - '/pypi-packages.yml'
      - '/debian-packages.yml'
      - '/python.yml'

variables:
  APTLY_BASE_REPOSITORY: common

stages:
  - test
  - build
  - publish

.unit test and feature test base:
  script:
    - !reference [.add repositories, script]
    - pip install --no-cache-dir -r requirements/test.txt
    - pip install .

.unit test and feature test add mariadb repository:
  script:
    - |
      cat > /etc/apt/sources.list.d/mariadb.sources << EOF
      Architectures: amd64 arm64 ppc64el
      Components: main
      X-Repolib-Name: mariadb
      Signed-By: /etc/apt/keyrings/mariadb.asc
      Suites: $DEBIAN_CODENAME
      Types: deb
      URIs: https://mirror.mariadb.org/repo/$MARIADB_VERSION/debian
      EOF
    - curl https://mariadb.org/mariadb_release_signing_key.asc -o /etc/apt/keyrings/mariadb.asc
    - apt-get update
    - apt-get -y install mariadb-server

.unit test and feature test add postgresql repository:
  script:
    - |
      cat > /etc/apt/sources.list.d/postgresql.sources << EOF
      Components: main
      X-Repolib-Name: postgresql
      Signed-By: /etc/apt/keyrings/postgresql.asc
      Suites: $DEBIAN_CODENAME-pgdg
      Types: deb
      URIs: http://apt.postgresql.org/pub/repos/apt
      EOF
    - curl https://www.postgresql.org/media/keys/ACCC4CF8.asc -o /etc/apt/keyrings/postgresql.asc
    - apt-get update
    - apt-get -y install postgresql-$POSTGRESQL_VERSION

unit test and feature test postgresql:
  stage: test
  image: python:3.11
  services:
    - name: postgres:$POSTGRESQL_VERSION
      alias: postgres-gw0
    - name: postgres:$POSTGRESQL_VERSION
      alias: postgres-gw1
    - name: postgres:$POSTGRESQL_VERSION
      alias: postgres-gw2
  variables:
    POSTGRES_PASSWORD: 'AxXpDrd8hdEequRTNzKE6U6k'
  script:
    - !reference [.unit test and feature test base, script]
    - !reference [.unit test and feature test add postgresql repository, script]
    # -n may not be higher than the amount of services above
    - pytest -n 3 tests/ -m postgresql -vvv --junitxml=report-pytest.xml
      --mariadb-server-host=mariadb --postgresql-server-host=postgres --postgresql-server-password='AxXpDrd8hdEequRTNzKE6U6k' --mariadb-server-password='D8nngLmktFW7ACDWHvdRtmrV'
  artifacts:
    reports:
      junit: report-*.xml
  parallel:
    matrix:
      # Supported versions
      - POSTGRESQL_VERSION: '13'
      - POSTGRESQL_VERSION: '14'
      - POSTGRESQL_VERSION: '15'
      - POSTGRESQL_VERSION: '16'

unit test and feature test mariadb:
  stage: test
  image: python:3.11-bookworm
  services:
    - name: mariadb:$MARIADB_VERSION
      alias: mariadb-gw0
    - name: mariadb:$MARIADB_VERSION
      alias: mariadb-gw1
    - name: mariadb:$MARIADB_VERSION
      alias: mariadb-gw2
  variables:
    MYSQL_ROOT_PASSWORD: 'D8nngLmktFW7ACDWHvdRtmrV'
    MYSQL_ROOT_HOST: '%'
  script:
    - !reference [.unit test and feature test base, script]
    - !reference [.unit test and feature test add mariadb repository, script]
    # -n may not be higher than the amount of services above
    - pytest -n 3 tests/ -m mariadb -vvv --junitxml=report-pytest.xml
      --mariadb-server-host=mariadb --postgresql-server-host=postgres --postgresql-server-password='AxXpDrd8hdEequRTNzKE6U6k' --mariadb-server-password='D8nngLmktFW7ACDWHvdRtmrV'
  artifacts:
    reports:
      junit: report-*.xml
  parallel:
    matrix:
      # LTS versions
      - MARIADB_VERSION: '10.11'
      - MARIADB_VERSION: '11.4'

# Previous unit tests and feature tests run for multiple versions of specific database server
# software. As those unit tests and feature tests run for specific pytest markers, they do not
# run with coverage. This unit test and feature test runs all tests for the most commonly used
# server software, with coverage.

unit test and feature test:
  stage: test
  image: python:3.11-bookworm
  services:
    # Latest major versions
    - name: mariadb:11.5
      alias: mariadb-gw0
    - name: mariadb:11.5
      alias: mariadb-gw1
    - name: mariadb:11.5
      alias: mariadb-gw2
    - name: postgres:18
      alias: postgres-gw0
    - name: postgres:18
      alias: postgres-gw1
    - name: postgres:18
      alias: postgres-gw2
  variables:
    POSTGRES_PASSWORD: 'AxXpDrd8hdEequRTNzKE6U6k'
    MYSQL_ROOT_PASSWORD: 'D8nngLmktFW7ACDWHvdRtmrV'
    MYSQL_ROOT_HOST: '%'
  script:
    - export MARIADB_VERSION=10.11
    - export POSTGRESQL_VERSION=14
    - !reference [.unit test and feature test base, script]
    - !reference [.unit test and feature test add mariadb repository, script]
    - !reference [.unit test and feature test add postgresql repository, script]
    # -n may not be higher than the amount of services above
    - pytest -n 3 tests/ -vvv --cov-branch --cov=cyberfusion.DatabaseSupport --cov-config=.coveragerc --cov-fail-under=95 --junitxml=report-pytest.xml
      --mariadb-server-host=mariadb --postgresql-server-host=postgres --postgresql-server-password='AxXpDrd8hdEequRTNzKE6U6k' --mariadb-server-password='D8nngLmktFW7ACDWHvdRtmrV'
  artifacts:
    reports:
      junit: report-*.xml
